apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: tienda
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: 122194780255.dkr.ecr.us-east-1.amazonaws.com/tienda-perritos-frontend:eks-v2
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 3
          resources:
            requests:
              cpu: "100m"
            limits:
              cpu: "300m"